language: php
env:
  global:
    - CC_TEST_REPORTER_ID=ad000d3c22dfe5d9d272db6192030b5dfb6d8900a63ba39d11aa67ae2c9d26e7
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

matrix:
  include:
    - php: '7.3'
      env: 'ORCHESTRA_VERSION=6.*'
    - php: '7.4'
      env: 'ORCHESTRA_VERSION=6.*'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ $(phpenv version-name) = "7.3" ]; then ./cc-test-reporter before-build; fi

install:
  - 'composer config github-oauth.github.com ${GH_TOKEN};'
  - 'composer remove --dev --no-update orchestra/testbench'
  - 'composer require --dev --prefer-dist --no-interaction orchestra/testbench $ORCHESTRA_VERSION'
  - 'composer install'

script: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml'

after_script:
  - 'if [ $(phpenv version-name) = "7.3" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi'
